# Site settings
title: Anna Klenkar
description: K1ENKS NYC
baseurl: "/index" # the subpath of your site, e.g. /blog
url: "http://k1enks.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anna Klenkar
user_description: Real Estate Professional at Compass
user_title: k1enks
email: anna.klenkar@compass.com
twitter_username: annaklenkar
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
